linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - whitespace
