status = [
    'Build (Go 1.15, OS ubuntu-latest)',
    'Build (Go 1.14, OS ubuntu-latest)',
    'Build (Go 1.15, OS macos-latest)',
    'Build (Go 1.14, OS macos-latest)',
    'runner / golangci-lint',
]


required_approvals = 1
delete_merged_branches = true
timeout-sec = 1800