name: CI

on: [ push, pull_request ]

jobs:
  build:
    name: Build (Go ${{ matrix.go }}, OS ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go: [ 1.14, 1.15 ]
        os: [ ubuntu-latest, macos-latest ]
    env:
      GO111MODULE: on
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Show versions
        run: go version

      - name: Install Go dependencies
        run: go mod download

      - name: Run golang tests
        run: |
          go test -v -coverprofile=backoff.txt -race ./tests/backoff
          go test -v -coverprofile=happyScenario.txt -race ./tests/happyScenario
          go test -v -coverprofile=interfaces.txt -race ./tests/interfaces
          go test -v -coverprofile=issues.txt -race ./tests/issues
          go test -v -coverprofile=stress.txt -race ./tests/stress

          go test -race -v -coverprofile=endure.txt -covermode=atomic

      - name: Run code coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          if [[ "$CODECOV_TOKEN" != "" ]]; then
            curl https://codecov.io/bash -o codecov-bash
            chmod +x codecov-bash
            ./codecov-bash -f backoff.txt
            ./codecov-bash -f happyScenario.txt
            ./codecov-bash -f interfaces.txt
            ./codecov-bash -f issues.txt
            ./codecov-bash -f stress.txt
          fi

  golangci-check:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.github_token }}
