name: CI

on: [ push, pull_request ]

jobs:
  build:
    name: Build (Go ${{ matrix.go }}, OS ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go: [ 1.14, 1.15 ]
        os: [ ubuntu-latest, macos-latest ]
    env:
      GO111MODULE: on
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Show versions
        run: go version

      - name: Install Go dependencies
        run: go mod download

      - name: Run golang tests
        run: |
          go test ./tests/backoff -race -v -coverprofile=backoff.txt -covermode=atomic
          go test ./tests/happy_scenarios -race -v -coverprofile=happy_scenarios.txt -covermode=atomic
          go test ./tests/interfaces -race -v -coverprofile=interfaces.txt -covermode=atomic
          go test ./tests/issues -race -v -coverprofile=issues.txt -covermode=atomic
          go test ./tests/stress -race -v -coverprofile=stress.txt -covermode=atomic
          go test ./tests/disabled_vertices -race -v -coverprofile=disabled_vertices.txt -covermode=atomic

      - name: Run code coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: backoff.txt, happy_scenarios.txt, interfaces.txt, issues.txt, stress.txt, disabled_vertices.txt
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true

  golangci-check:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.github_token }}
