name: macOS

on:
  push:
  pull_request:
    branches:
      # Branches from forks have the form 'user:branch-name' so we only run
      # this job on pull_request events for branches that look like fork
      # branches. Without this we would end up running this job twice for non
      # forked PRs, once for the push and then once for opening the PR.
      - '**:**'

jobs:
  build:
    name: Tests (Go ${{ matrix.go }}, OS ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        go: [ 1.14, 1.15 ]
        os: [ macos-latest ]
    env:
      GO111MODULE: on
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Show versions
        run: go version

      - name: Install Go dependencies
        run: go mod download

      - name: Run golang tests on ${{ matrix.os }}
        run: |
          go test -v -race -cover -tags=debug ./tests/backoff
          go test -v -race -cover -tags=debug ./tests/happy_scenarios
          go test -v -race -cover -tags=debug ./tests/interfaces
          go test -v -race -cover -tags=debug ./tests/issues
          go test -v -race -cover -tags=debug ./tests/stress
          go test -v -race -cover -tags=debug ./tests/disabled_vertices

